"""add string represatation of user profile_image

Revision ID: 0809ee2bf25a
Revises: 4ed1f62bf8cb
Create Date: 2023-12-21 18:26:17.055455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0809ee2bf25a'
down_revision: Union[str, None] = '4ed1f62bf8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'message', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    # ### end Alembic commands ###
