"""add relationship with username instead of user id

Revision ID: 1d40d9a9abb1
Revises: 314818f7614a
Create Date: 2023-12-10 10:37:12.019724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d40d9a9abb1'
down_revision: Union[str, None] = '314818f7614a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('username', sa.String(), nullable=True))
    op.drop_constraint('message_user_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['username'], ['username'])
    op.drop_column('message', 'user_id')
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.add_column('message', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_user_id_fkey', 'message', 'user', ['user_id'], ['id'])
    op.drop_column('message', 'username')
    # ### end Alembic commands ###
