"""add relationship message and user

Revision ID: 314818f7614a
Revises: c98e684a2dde
Create Date: 2023-12-10 08:42:54.374658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '314818f7614a'
down_revision: Union[str, None] = 'c98e684a2dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'user_id')
    # ### end Alembic commands ###
