"""Add profile image to User model

Revision ID: 4ed1f62bf8cb
Revises: 1d40d9a9abb1
Create Date: 2023-12-20 17:50:33.625338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed1f62bf8cb'
down_revision: Union[str, None] = '1d40d9a9abb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###
