"""Add relations to Message and User models

Revision ID: c7a967488d3e
Revises: 9033490c59bd
Create Date: 2023-12-09 13:19:24.579613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a967488d3e'
down_revision: Union[str, None] = '9033490c59bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'user_id')
    # ### end Alembic commands ###
